import type { Metadata } from "next";
import localFont from "next/font/local";
// import "./globals.css";
import Providers from "@/src/redux/providers";
import "@/src/styles/index.scss";
import TabsComponent from "@/src/components/tabs/TabsComponent";
import dynamic from "next/dynamic";
import { ToastContainer } from "react-toastify";

const AnimatedCursor = dynamic(() => import("react-animated-cursor"), {
  ssr: false,
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Multisoft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AnimatedCursor
            innerSize={8}
            outerSize={44}
            color="40, 107, 206"
            outerAlpha={0.3}
            innerScale={0.7}
            outerScale={1.2}
          />
          {children}
          <TabsComponent />
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
